mealplans/urls.py
from django.urls import path


from mealplans.views import (
    MealPlanListView,
    MealPlanCreateView,
    MealPlanDetailView,
    MealPlanDeleteView,
    MealPlanUpdateView,
)

urlpatterns = [
    path("", MealPlanListView.as_view(), name="mealplans_list"),
    path("<int:pk>/", MealPlanDetailView.as_view(), name="mealplan_detail"),
    path(
        "<int:pk>/delete/", MealPlanDeleteView.as_view(), name="mealplan_delete"
    ),
    path("new/", MealPlanCreateView.as_view(), name="mealplan_new"),
    path("<int:pk>/edit/", MealPlanUpdateView.as_view(), name="mealplan_edit"),
]

scrumptious/urls.py
from django.contrib.auth import views as auth_views

from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path("mealplans/", include("mealplans.urls")),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("account/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagDeleteView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
]

mealplans/models.py
from email.charset import add_charset, add_codec
from msilib import add_data
import datetime
from django.db import models

from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL
# Create your models here.


class Mealplan(models.Model):
    name = models.CharField(max_length=120)
    owner = models.ForeignKey(
        USER_MODEL,
        on_delete=models.CASCADE,
    )
    date = models.DateField()
    recipes = models.ManyToManyField("recipes.Recipe", related_name="recipes")

mealplans/views.py
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from mealplans.models import Mealplan


class MealPlanListView(ListView):
    model = Mealplan
    template_name = "mealplans/list.html"
    paginate_by = 2

    def get_queryset(self):
        queryset = super().get_queryset()
        print(queryset)
        return queryset


class MealPlanDetailView(LoginRequiredMixin, DetailView):
    model = Mealplan
    template_name = "mealplans/detail.html"


class MealPlanCreateView(CreateView):
    model = Mealplan
    template_name = "mealplans/new.html"
    fields = ["name", "recipes", "date"]
    success_url = reverse_lazy("mealplans_list")

    def form_valid(self, form):
        plan = form.save(commit=False)
        plan.owner = self.request.user
        plan.save()
        form.save_m2m()
        return redirect("mealplan_detail", pk=plan.id)


class MealPlanUpdateView(LoginRequiredMixin, UpdateView):
    model = Mealplan
    template_name = "mealplans/edit.html"
    fields = ["name", "recipes", "date"]
    success_url = reverse_lazy("meals_list")


class MealPlanDeleteView(LoginRequiredMixin, DeleteView):
    model = Mealplan
    template_name = "mealplans/delete.html"
    success_url = reverse_lazy("mealplans_list")

mealplans/templates/mealplans/delete.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
{% if user.username == mealplan.owner.username %}
<main>
    <div class="delete-form">
        <form method="post">
            {% csrf_token %}
            <h3>Are you sure you want to delete "{{ mealplan.name }}"?</h3>
            {{ form.as_p }}
            <div>
                <button class="button">Delete</button>
            </div>
        </form>
    </div>
</main>
{% endif %}
{% endblock content %}

mealplans/templates/mealplans/detail.html
{% extends 'base.html' %}

{% load static %}
{% load markdownify %}

{% block content %}
{% if user.username == mealplan.owner.username %}
<main class="mealplans-detail">
    <div>
        <a href="{% url 'mealplan_edit' mealplan.id %}">Edit</a>
        <a href="{% url 'mealplan_delete' mealplan.id %}">Delete</a>
    </div>
    <h2>Recipes for {{ mealplan.name }}</h2>
    {% for recipe in mealplan.recipes.all %}
    <p>
        <a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name }}</a>
    </p>
    {% endfor %}

    <P>Meal plan to be served on {{mealplan.date}}.</P>
</main>
{% endif %}
{% endblock content %}

mealplans/templates/mealplans/edit.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
{% if user.username == mealplan.owner.username %}
<main class="recipe-form">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="control">
            <button class="button">Update</button>
        </div>
    </form>
</main>
{% endif %}
{% endblock content %}

mealplans/templates/mealplans/list.html
{% extends 'base.html' %}

{% load static %}

{% block pagination %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock pagination %}

{% block content %}
<main>
    {% for mealplan in mealplan_list %}
    <div>
        {% if user.username == mealplan.owner.username %}
        <h2>
            <a href="{% url 'mealplan_detail' mealplan.id %}">{{ mealplan.name }}</a>
        </h2>
        {% for recipe in mealplan.recipes.all %}
        <p>
            <a href="{% url 'mealplan_detail' recipe.pk %}">{{ recipe.name }}</a>
        </p>
        {% endfor %}
        {% endif %}
    </div>
    {% empty %}
    <div>
        <h1>No meals, yet</h1>
    </div>
    {% endfor %}
    <p>
        Would you like to
        <a href="{% url 'mealplan_new' %}">create</a>
        a new meal plan?
    </p>
</main>
{% endblock content %}

mealplans/templates/mealplans/new.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<main class="recipe-form">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="control">
            <button class="button">Create</button>
        </div>
    </form>
</main>
{% endblock content %}